menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/appl
    GitHub: https://github.com/solos
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 
    on: true
    domain: solos

# Analytics
# google-analytics:
#ga: UA-65933410-1

# Copyright Infomation
startyear: 2012

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
